FROM amazoncorretto:11-alpine-jdk//de que imagen partimos
MAINTAINER LRR //quien es el dueño de la imagen
COPY  //va a copiar el empaquetado  github
ENTRYPOINT //es la instruccion que se va a ejecutar primero 
